# Generated by Django 4.1.1 on 2022-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIPDosen', models.CharField(max_length=30)),
                ('NAMA', models.CharField(max_length=30)),
                ('TTL', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=30)),
                ('FAKULTAS', models.CharField(max_length=30)),
                ('PRODI', models.CharField(max_length=30)),
                ('ALAMAT', models.CharField(max_length=30)),
                ('PHOTO', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.CharField(max_length=30)),
                ('NAMA', models.CharField(max_length=30)),
                ('TTL', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=30)),
                ('FAKULTAS', models.CharField(max_length=30)),
                ('PRODI', models.CharField(max_length=30)),
                ('ALAMAT', models.CharField(max_length=30)),
                ('PHOTO', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIPTendik', models.CharField(max_length=30)),
                ('NAMA', models.CharField(max_length=30)),
                ('TTL', models.CharField(max_length=30)),
                ('EMAIL', models.CharField(max_length=30)),
                ('FAKULTAS', models.CharField(max_length=30)),
                ('PRODI', models.CharField(max_length=30)),
                ('ALAMAT', models.CharField(max_length=30)),
                ('PHOTO', models.CharField(max_length=30)),
            ],
        ),
    ]
